-- Hand-written schema 4 sample in the SavedVariables format of the professions plan appendix (not generated by the
-- Lua harness): one entry or more for every professions table, plus items with classID/subclassID.
ForeverLedgerDB = {
	["meta"] = {
		["schemaVersion"] = 4,
		["addonVersion"] = "0.3.0",
		["build"] = 69977,
		["version"] = "1.60.1",
		["interface"] = 16001,
		["session"] = "1790100000-c0de",
	},
	["chars"] = {
		["Thibodeaux-Bayou"] = {
			["class"] = "HUNTER",
			["faction"] = "Alliance",
			["lastSeen"] = 1790100900,
			["level"] = 12,
			["name"] = "Thibodeaux",
			["race"] = "Human",
			["realm"] = "Bayou",
		},
	},
	["items"] = {
		[2589] = {
			["name"] = "Linen Cloth",
			["quality"] = 1,
			["type"] = "Trade Goods",
			["subtype"] = "Cloth",
			["equipLoc"] = "",
			["classID"] = 7,
			["subclassID"] = 5,
		},
		[2996] = {
			["name"] = "Bolt of Linen Cloth",
			["quality"] = 1,
			["type"] = "Trade Goods",
			["subtype"] = "Cloth",
			["classID"] = 7,
			["subclassID"] = 5,
		},
		[6270] = {
			["name"] = "Pattern: Blue Linen Vest",
			["quality"] = 2,
			["type"] = "Recipe",
			["subtype"] = "Tailoring",
			["classID"] = 9,
			["subclassID"] = 2,
			["byBuild"] = {
				[69977] = {
					["firstSeen"] = 1790100300,
					["sellPrice"] = 50,
					["stats"] = {
					},
					["tooltip"] = {
						"Pattern: Blue Linen Vest", -- [1]
						"Requires Tailoring (70)", -- [2]
						"Use: Teaches you how to sew a Blue Linen Vest.", -- [3]
					},
				},
			},
		},
	},
	["skills"] = {
		["Thibodeaux-Bayou"] = {
			[197] = {
				["name"] = "Tailoring",
				["rank"] = 12,
				["maxRank"] = 75,
				["modifier"] = 0,
				["parentID"] = 0,
				["lastSeen"] = 1790100900,
			},
			[186] = {
				["name"] = "Mining",
				["rank"] = 31,
				["maxRank"] = 75,
				["lastSeen"] = 1790100900,
			},
		},
	},
	["skillUps"] = {
		{
			["char"] = "Thibodeaux-Bayou",
			["skillLineID"] = 197,
			["from"] = 11,
			["to"] = 12,
			["build"] = 69977,
			["time"] = 1790100420,
			["recipeID"] = 2963,
		}, -- [1]
		{
			["char"] = "Thibodeaux-Bayou",
			["skillLineID"] = 186,
			["from"] = 30,
			["to"] = 31,
			["build"] = 69977,
			["time"] = 1790100700,
		}, -- [2]
	},
	["recipes"] = {
		[2963] = {
			["id"] = 2963,
			["name"] = "Bolt of Linen Cloth",
			["skillLineID"] = 197,
			["categoryID"] = 1001,
			["byBuild"] = {
				[69977] = {
					["outputItemID"] = 2996,
					["qtyMin"] = 1,
					["qtyMax"] = 1,
					["reagents"] = {
						{
							["itemID"] = 2589,
							["qty"] = 2,
						}, -- [1]
					},
					["maxTrivial"] = 25,
					["firstSeen"] = 1790100400,
				},
			},
		},
		[7629] = {
			["id"] = 7629,
			["name"] = "Blue Linen Vest",
			["skillLineID"] = 197,
			["byBuild"] = {
				[69977] = {
					["outputItemID"] = 6240,
					["qtyMin"] = 1,
					["qtyMax"] = 1,
					["reagents"] = {
						{
							["itemID"] = 2996,
							["qty"] = 3,
						}, -- [1]
						{
							["itemID"] = 2320,
							["qty"] = 1,
						}, -- [2]
					},
					["sourceText"] = "Pattern: Blue Linen Vest",
					["firstSeen"] = 1790100400,
				},
			},
		},
	},
	["recipeSeen"] = {
		[69977] = {
			["Thibodeaux-Bayou"] = {
				[2963] = {
					["learned"] = true,
					["difficulty"] = "optimal",
					["rank"] = 12,
					["seenAt"] = 1790100420,
					["byDifficulty"] = {
						["optimal"] = {
							["minRank"] = 1,
							["maxRank"] = 12,
						},
					},
				},
				[7629] = {
					["learned"] = false,
					["seenAt"] = 1790100420,
					["byDifficulty"] = {
					},
				},
			},
		},
	},
	["learned"] = {
		{
			["char"] = "Thibodeaux-Bayou",
			["recipeID"] = 2963,
			["build"] = 69977,
			["time"] = 1790100200,
			["via"] = "trainer:1346",
		}, -- [1]
		{
			["char"] = "Thibodeaux-Bayou",
			["recipeID"] = 7629,
			["build"] = 69977,
			["time"] = 1790100500,
			["via"] = "item:6270",
		}, -- [2]
	},
	["crafts"] = {
		[69977] = {
			[2963] = {
				["casts"] = 4,
				["qty"] = 4,
				["procs"] = 0,
				["skillUps"] = 2,
			},
		},
	},
	["nodes"] = {
		[69977] = {
			[1731] = {
				["opened"] = 3,
				["name"] = "Copper Vein",
				["rankMin"] = 29,
				["skillLineID"] = 186,
				["spots"] = {
					[1429] = {
						"45.1,33.2", -- [1]
						"46,34.5", -- [2]
					},
				},
			},
			[0] = {
				["opened"] = 2,
				["skillLineID"] = 356,
				["spots"] = {
					[1429] = {
						"50,60", -- [1]
					},
				},
			},
		},
	},
	["nodeLoot"] = {
		[2770] = {
			[69977] = {
				[1731] = {
					["n"] = 3,
					["qty"] = 5,
				},
			},
		},
		[2835] = {
			[69977] = {
				[1731] = {
					["n"] = 1,
					["qty"] = 1,
				},
			},
		},
		[6303] = {
			[69977] = {
				[0] = {
					["n"] = 2,
					["qty"] = 2,
				},
			},
		},
	},
	["trainers"] = {
		[69977] = {
			[1346] = {
				["name"] = "Georgio Bolero",
				["loc"] = {
					["zone"] = "Stormwind City",
					["subzone"] = "The Canals",
					["mapID"] = 1453,
					["x"] = 43.4,
					["y"] = 73.8,
				},
				["skillLineID"] = 197,
				["seenAt"] = 1790100150,
				["services"] = {
					{
						["name"] = "Bolt of Linen Cloth",
						["type"] = "used",
						["cost"] = 0,
						["skill"] = "Tailoring",
						["skillRank"] = 0,
						["level"] = 0,
						["itemID"] = 2996,
					}, -- [1]
					{
						["name"] = "Brown Linen Shirt",
						["type"] = "available",
						["cost"] = 50,
						["skill"] = "Tailoring",
						["skillRank"] = 10,
						["level"] = 5,
						["itemID"] = 4344,
					}, -- [2]
				},
			},
		},
	},
	["vendors"] = {
		[69977] = {
			[1347] = {
				["name"] = "Alexandra Bolero",
				["loc"] = {
					["zone"] = "Stormwind City",
					["subzone"] = "The Canals",
					["mapID"] = 1453,
					["x"] = 43.2,
					["y"] = 74.1,
				},
				["seenAt"] = 1790100160,
				["items"] = {
					{
						["itemID"] = 2320,
						["price"] = 10,
						["stack"] = 1,
						["numAvailable"] = -1,
					}, -- [1]
					{
						["itemID"] = 6270,
						["price"] = 200,
						["stack"] = 1,
						["numAvailable"] = 1,
						["extendedCost"] = false,
					}, -- [2]
				},
			},
		},
	},
	["apiSamples"] = {
		["C_TradeSkillUI.GetRecipeInfo"] = {
			["build"] = 69977,
			["time"] = 1790100400,
			["sample"] = {
				["recipeID"] = 2963,
				["name"] = "Bolt of Linen Cloth",
				["learned"] = true,
				["relativeDifficulty"] = 0,
				["categoryID"] = 1001,
			},
		},
		["TRADE_SKILL_ITEM_CRAFTED_RESULT"] = {
			["build"] = 69977,
			["time"] = 1790100420,
			["sample"] = {
				{
					["itemID"] = 2996,
					["quantity"] = 1,
					["multicraft"] = 0,
				}, -- [1]
			},
		},
	},
}
