import { randomUUID } from 'node:crypto';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { ConfigError } from './errors.js';
import { readJsonIfExists, writeJsonAtomic } from './fsutil.js';

/** What is stored in config.json. */
export interface ConfigFile {
  /** WoW install folder, flavor folder (`_classic_era_`-style) or its WTF folder. */
  wowPath?: string;
  /** WoW account folder names to upload; empty = every account that has a ForeverLedger.lua. */
  accounts: string[];
  serverUrl?: string;
  token?: string;
  /** Random id for this install, generated by `init`. */
  uploaderId: string;
  /** Queue + ack state; defaults to `<config dir>/state`. */
  stateDir?: string;
}

/** Config as used at runtime: paths resolved, defaults filled in. */
export interface Config extends ConfigFile {
  configPath: string;
  stateDir: string;
}

export interface PathEnv {
  platform?: NodeJS.Platform;
  env?: NodeJS.ProcessEnv;
  home?: string;
}

/** `%APPDATA%\forever-ledger\config.json` on Windows, XDG config dir elsewhere. */
export function defaultConfigPath(opts: PathEnv = {}): string {
  const env = opts.env ?? process.env;
  const platform = opts.platform ?? process.platform;
  const home = opts.home ?? homedir();
  if (env.FOREVER_LEDGER_CONFIG) return resolve(env.FOREVER_LEDGER_CONFIG);
  if (platform === 'win32') {
    const appData = env.APPDATA ?? join(home, 'AppData', 'Roaming');
    return join(appData, 'forever-ledger', 'config.json');
  }
  const xdg = env.XDG_CONFIG_HOME ?? join(home, '.config');
  return join(xdg, 'forever-ledger', 'config.json');
}

/** `--config` wins over `FOREVER_LEDGER_CONFIG`, which wins over the platform default. */
export function resolveConfigPath(cliPath?: string, opts: PathEnv = {}): string {
  return cliPath ? resolve(cliPath) : defaultConfigPath(opts);
}

const isObj = (v: unknown): v is Record<string, unknown> =>
  typeof v === 'object' && v !== null && !Array.isArray(v);

function optionalString(raw: Record<string, unknown>, key: string, issues: string[]) {
  const v = raw[key];
  if (v === undefined || v === null || v === '') return undefined;
  if (typeof v !== 'string') {
    issues.push(`${key}: expected a string`);
    return undefined;
  }
  return v.trim();
}

/** Normalises a server URL: must be http(s), no trailing slash. */
export function normalizeServerUrl(value: string): string {
  let url: URL;
  try {
    url = new URL(value);
  } catch {
    throw new ConfigError(`serverUrl "${value}" is not a valid URL`);
  }
  if (url.protocol !== 'http:' && url.protocol !== 'https:')
    throw new ConfigError(`serverUrl must start with http:// or https:// (got "${value}")`);
  return url.toString().replace(/\/+$/, '');
}

/** Validates the parsed JSON of a config file. Throws ConfigError listing every problem. */
export function validateConfigFile(raw: unknown): ConfigFile {
  if (!isObj(raw)) throw new ConfigError('config must be a JSON object');
  const issues: string[] = [];

  const wowPath = optionalString(raw, 'wowPath', issues);
  const token = optionalString(raw, 'token', issues);
  const stateDir = optionalString(raw, 'stateDir', issues);
  let serverUrl = optionalString(raw, 'serverUrl', issues);
  if (serverUrl !== undefined) {
    try {
      serverUrl = normalizeServerUrl(serverUrl);
    } catch (err) {
      issues.push((err as Error).message);
    }
  }

  let accounts: string[] = [];
  if (raw.accounts !== undefined) {
    if (!Array.isArray(raw.accounts) || raw.accounts.some((a) => typeof a !== 'string' || a === ''))
      issues.push('accounts: expected an array of account folder names');
    else accounts = raw.accounts as string[];
  }

  const uploaderId = optionalString(raw, 'uploaderId', issues);
  if (uploaderId === undefined) issues.push('uploaderId: missing (run `forever-ledger init`)');
  else if (uploaderId.length > 128) issues.push('uploaderId: at most 128 characters');

  if (issues.length) throw new ConfigError(`invalid config:\n  - ${issues.join('\n  - ')}`);
  return { wowPath, accounts, serverUrl, token, uploaderId: uploaderId as string, stateDir };
}

export function resolveConfig(file: ConfigFile, configPath: string): Config {
  const base = dirname(configPath);
  return {
    ...file,
    wowPath: file.wowPath ? resolve(base, file.wowPath) : undefined,
    stateDir: file.stateDir ? resolve(base, file.stateDir) : join(base, 'state'),
    configPath,
  };
}

export async function readConfigFile(configPath: string): Promise<ConfigFile | undefined> {
  let raw: unknown;
  try {
    raw = await readJsonIfExists(configPath);
  } catch (err) {
    throw new ConfigError(`cannot read ${configPath}: ${(err as Error).message}`);
  }
  return raw === undefined ? undefined : validateConfigFile(raw);
}

export async function loadConfig(configPath: string): Promise<Config> {
  const file = await readConfigFile(configPath);
  if (!file)
    throw new ConfigError(
      `no config at ${configPath}: run \`forever-ledger init --wow-path <WoW folder>\` first`,
    );
  return resolveConfig(file, configPath);
}

/** Writes config.json (owner-only permissions where the OS supports them: it holds the token). */
export async function saveConfig(configPath: string, file: ConfigFile): Promise<void> {
  const out: Record<string, unknown> = { ...file };
  for (const k of Object.keys(out)) if (out[k] === undefined) delete out[k];
  await writeJsonAtomic(configPath, out, { mode: 0o600 });
}

export const newUploaderId = () => randomUUID();

/** `abcd…wxyz` — enough to recognise a token without printing it. */
export function maskToken(token: string | undefined): string {
  if (!token) return '(not set)';
  return token.length <= 8 ? '********' : `${token.slice(0, 4)}…${token.slice(-4)}`;
}

/** Throws unless serverUrl and token are set (needed for anything that talks to the server). */
export function requireServer(config: Config): { serverUrl: string; token: string } {
  if (!config.serverUrl || !config.token)
    throw new ConfigError(
      `serverUrl and token must be set in ${config.configPath} (run \`forever-ledger init --server <url> --token <token>\`)`,
    );
  return { serverUrl: config.serverUrl, token: config.token };
}
