/**
 * Whether a page is a bot challenge or block page (Cloudflare interstitial, CloudFront block) rather than content.
 * The worker checks too; this is the server's backstop so a challenge page is never stored as a snapshot. Normal
 * Cloudflare-fronted pages load `/cdn-cgi/challenge-platform/` scripts, so that alone is not a challenge.
 */
const TITLES = [
  /^just a moment/i,
  /^attention required/i,
  /^access denied/i,
  /request could not be satisfied/i,
  /^verifying you are human/i,
  /^security check/i,
  /^ddos-guard/i,
];

export function looksLikeChallenge(html: string): boolean {
  const title = /<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1]?.trim() ?? '';
  if (TITLES.some((t) => t.test(title))) return true;
  if (/window\._cf_chl_opt\b/.test(html)) return true;
  if (/id=["']challenge-(form|running|stage)["']/.test(html)) return true;
  return /Generated by cloudfront \(CloudFront\)/i.test(html) && /Request blocked/i.test(html);
}
