// Generated by apps/server/scripts/planner-taxi.ts from fixtures/real/probe-70245-travel.json (probe 0.6.0, build
// 70245, GetTaxiNodesForMap 1414 / 1415). Flight master node id → faction ('both' = neutral). Do not edit by hand.
export const TAXI_NODE_FACTIONS: Readonly<Record<number, 'Horde' | 'Alliance' | 'both'>> = {
  2: 'Alliance', // Stormwind, Elwynn
  4: 'Alliance', // Sentinel Hill, Westfall
  5: 'Alliance', // Lakeshire, Redridge
  6: 'Alliance', // Ironforge, Dun Morogh
  7: 'Alliance', // Menethil Harbor, Wetlands
  8: 'Alliance', // Thelsamar, Loch Modan
  10: 'Horde', // The Sepulcher, Silverpine Forest
  11: 'Horde', // Undercity, Tirisfal
  12: 'Alliance', // Darkshire, Duskwood
  13: 'Horde', // Tarren Mill, Hillsbrad
  14: 'Alliance', // Southshore, Hillsbrad
  16: 'Alliance', // Refuge Pointe, Arathi
  17: 'Horde', // Hammerfall, Arathi
  18: 'Horde', // Booty Bay, Stranglethorn
  19: 'Alliance', // Booty Bay, Stranglethorn
  20: 'Horde', // Grom'gol, Stranglethorn
  21: 'Horde', // Kargath, Badlands
  22: 'Horde', // Thunder Bluff, Mulgore
  23: 'Horde', // Orgrimmar, Durotar
  25: 'Horde', // Crossroads, The Barrens
  26: 'Alliance', // Auberdine, Darkshore
  27: 'Alliance', // Rut'theran Village, Teldrassil
  28: 'Alliance', // Astranaar, Ashenvale
  29: 'Horde', // Sun Rock Retreat, Stonetalon Mountains
  30: 'Horde', // Freewind Post, Thousand Needles
  31: 'Alliance', // Thalanaar, Feralas
  32: 'Alliance', // Theramore, Dustwallow Marsh
  33: 'Alliance', // Stonetalon Peak, Stonetalon Mountains
  37: 'Alliance', // Nijel's Point, Desolace
  38: 'Horde', // Shadowprey Village, Desolace
  39: 'Alliance', // Gadgetzan, Tanaris
  40: 'Horde', // Gadgetzan, Tanaris
  41: 'Alliance', // Feathermoon, Feralas
  42: 'Horde', // Camp Mojache, Feralas
  43: 'Alliance', // Aerie Peak, The Hinterlands
  44: 'Horde', // Valormok, Azshara
  45: 'Alliance', // Nethergarde Keep, Blasted Lands
  48: 'Horde', // Bloodvenom Post, Felwood
  49: 'Alliance', // Moonglade
  52: 'Alliance', // Everlook, Winterspring
  53: 'Horde', // Everlook, Winterspring
  55: 'Horde', // Brackenwall Village, Dustwallow Marsh
  56: 'Horde', // Stonard, Swamp of Sorrows
  58: 'Horde', // Zoram'gar Outpost, Ashenvale
  61: 'Horde', // Splintertree Post, Ashenvale
  62: 'Alliance', // Nighthaven, Moonglade
  63: 'Horde', // Nighthaven, Moonglade
  64: 'Alliance', // Talrendis Point, Azshara
  65: 'Alliance', // Talonbranch Glade, Felwood
  66: 'Alliance', // Chillwind Camp, Western Plaguelands
  67: 'Alliance', // Light's Hope Chapel, Eastern Plaguelands
  68: 'Horde', // Light's Hope Chapel, Eastern Plaguelands
  69: 'Horde', // Moonglade
  70: 'Horde', // Flame Crest, Burning Steppes
  71: 'Alliance', // Morgan's Vigil, Burning Steppes
  72: 'Horde', // Cenarion Hold, Silithus
  73: 'Alliance', // Cenarion Hold, Silithus
  74: 'Alliance', // Thorium Point, Searing Gorge
  75: 'Horde', // Thorium Point, Searing Gorge
  76: 'Horde', // Revantusk Village, The Hinterlands
  77: 'Horde', // Camp Taurajo, The Barrens
  79: 'both', // Marshal's Refuge, Un'Goro Crater
  80: 'both', // Ratchet, The Barrens
  84: 'both', // Plaguewood Tower, Eastern Plaguelands
  85: 'both', // Northpass Tower, Eastern Plaguelands
  86: 'both', // Eastwall Tower, Eastern Plaguelands
  87: 'both', // Crown Guard Tower, Eastern Plaguelands
  559: 'both', // Summit of Eternity, Mount Hyjal
  3203: 'Horde', // Rog'mar, Riverglades
  3206: 'Horde', // zzOLDBolder'ok, Riverglades
  3207: 'Alliance', // zzOLDRiverglades, Farholde Keep
  3208: 'both', // zzOLDPowderfuse Port, Riverglades
  3242: 'both', // Tainted Foothills, Mount Hyjal
  3276: 'Alliance', // Farholde Keep, Riverglades
};
