// One-off generator: the probe's client map catalog → src/planner/maps.ts. Kept for the next probe run.
// Run: pnpm --filter @forever-ledger/server exec tsx scripts/planner-maps.ts
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../..');
const source = 'fixtures/real/probe-70245-travel.json';
const target = resolve(here, '../src/planner/maps.ts');

const FIELDS = [
  'id',
  'name',
  'mapType',
  'parentMapID',
  'width',
  'height',
  'c0',
  'x0',
  'y0',
  'c1',
  'x1',
  'y1',
];
type Row = [
  number,
  string,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
];

const dump = JSON.parse(readFileSync(resolve(root, source), 'utf8')) as {
  snapshot: { maps: { fields: string[]; rows: unknown[][] } };
};
const { fields, rows } = dump.snapshot.maps;
if (fields.join() !== FIELDS.join()) throw new Error(`unexpected map fields: ${fields.join()}`);

const kept: Row[] = [];
let skipped = 0;
for (const row of rows) {
  // Maps without world corners (GetWorldPosFromMapPos returned nothing) are written as false: no geometry, skip.
  if (row.slice(6).some((v) => typeof v !== 'number')) {
    skipped++;
    continue;
  }
  // Corners on two continents (947 Azeroth spans Kalimdor and the Eastern Kingdoms): no single world frame, skip.
  if (row[6] !== row[9]) {
    skipped++;
    continue;
  }
  kept.push(row as Row);
}
kept.sort((a, b) => a[0] - b[0]);

const out = `// Generated by apps/server/scripts/planner-maps.ts from ${source} (probe 0.6.0, build
// 70245). Rows: [id, name, mapType, parentMapID, width, height, c0, x0, y0, c1, x1, y1] (yards). Do not edit by hand.
export const MAP_ROWS: readonly (readonly [
  number,
  string,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
  number,
])[] = [
${kept.map((r) => `  ${JSON.stringify(r).replace(/,/g, ', ')},`).join('\n')}
];
`;
// Formatted like the rest of the repo, so `prettier --check` passes on the generated file as written.
const options = (await resolveConfig(target)) ?? {};
writeFileSync(target, await format(out, { ...options, filepath: target }));
console.log(
  `wrote ${kept.length} maps (${skipped} without corners or across continents skipped) to ${target}`,
);
