// One-off generator: the probe's flight master factions → src/planner/taxi-nodes.ts. Kept for the next probe run.
// Run: pnpm --filter @forever-ledger/server exec tsx scripts/planner-taxi.ts
//
// C_TaxiMap.GetTaxiNodesForMap(1414 / 1415) lists every node of a continent with its faction (1 Horde, 2 Alliance,
// 0 neutral); GetAllTaxiNodes (what the addon stores) has no faction. The table keys factions by node id.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '../../..');
const source = 'fixtures/real/probe-70245-travel.json';
const target = resolve(here, '../src/planner/taxi-nodes.ts');

interface ForMapNode {
  nodeID: number;
  name: string;
  faction: number;
}
const dump = JSON.parse(readFileSync(resolve(root, source), 'utf8')) as {
  snapshot: { taxi: Record<string, { forMap?: { nodes?: ForMapNode[] } }> };
};

const SIDE: Record<number, string> = { 1: 'Horde', 2: 'Alliance' };
const nodes = new Map<number, { name: string; side: string }>();
for (const continent of ['1414', '1415']) {
  for (const n of dump.snapshot.taxi[continent]?.forMap?.nodes ?? []) {
    const side = SIDE[n.faction] ?? 'both';
    const seen = nodes.get(n.nodeID);
    if (seen && seen.side !== side) throw new Error(`node ${n.nodeID}: ${seen.side} and ${side}`);
    nodes.set(n.nodeID, { name: n.name, side });
  }
}
const sorted = [...nodes].sort((a, b) => a[0] - b[0]);

const out = `// Generated by apps/server/scripts/planner-taxi.ts from ${source} (probe 0.6.0, build
// 70245, GetTaxiNodesForMap 1414 / 1415). Flight master node id → faction ('both' = neutral). Do not edit by hand.
export const TAXI_NODE_FACTIONS: Readonly<Record<number, 'Horde' | 'Alliance' | 'both'>> = {
${sorted.map(([id, n]) => `  ${id}: '${n.side}', // ${n.name}`).join('\n')}
};
`;
const options = (await resolveConfig(target)) ?? {};
writeFileSync(target, await format(out, { ...options, filepath: target }));
console.log(`wrote ${sorted.length} taxi node factions to ${target}`);
